export default {
  namespaced: true,
  name: 'products',

  state: () => ({
    brooklyn: {
      translateKey: 'brooklyn',
      tissues: [
        { imgName: 'Brooklynmood', color: '#E4DFDB' },
        { imgName: 'Brooklyn-sofamood', color: '#AEA196' },
      ],
      size: 'brooklynRozmir',
      carousel: ['Brooklyn1', 'Brooklyn2', 'Brooklyn3', 'Brooklyn4', 'Brooklyn5', 'Brooklyn6', 'Brooklyn7', 'Brooklyn8'],
    },
    elephant: {
      translateKey: 'elephant',
      tissues: [
        { imgName: 'Elephantmood', color: '#AEA196' },
        { imgName: 'Brooklynmood', color: '#E4DFDB' },
      ],
      size: 'elephantRozmir',
      carousel: [
        'Elephant1',
        'Elephant2',
        'Elephant3',
        'Elephant4',
        'Elephant5',
        'Elephant6',
        'Elephant7',
        'Elephant8',
        'Elephant9',
        'Elephant10',
      ],
    },
    bizetLux: {
      translateKey: 'bizetLux',
      tissues: [{ imgName: 'Bizet-luxmood', color: '' }],
      size: 'BizetRozmir',
      carousel: ['Bizet-lux1', 'Bizet-lux2'],
    },
    brooklynSofa: {
      translateKey: 'brooklynSofa',
      tissues: [
        { imgName: 'Brooklyn-sofamood', color: '#AEA196' },
        { imgName: 'Brooklynmood', color: '#E4DFDB' },
      ],
      size: 'brSofaRozmir',
      carousel: [
        'Brooklyn-sofa1',
        'Brooklyn-sofa2',
        'Brooklyn-sofa3',
        'Brooklyn-sofa4',
        'Brooklyn-sofa5',
        'Brooklyn-sofa6',
        'Brooklyn-sofa7',
        'Brooklyn-sofa8',
      ],
    },
    floransSlimChair: {
      translateKey: 'floransSlimChair',
      tissues: [
        { imgName: 'Florance Chairmood', color: '#c1bcbd' },
        { imgName: 'Florance ChairmoodB', color: '#65868f' },
        { imgName: 'Florance Chairmood1', color: '#ab6e59' },
        { imgName: 'Florance Chairmood2', color: '#907882' },
      ],
      size: 'FloranceSlimRozmir',
      carousel: [
        'Florance Slim Chair1',
        'Florance Slim Chair2',
        'Florance Slim Chair3',
        'Florance Slim Chair4',
        'Florance Slim Chair5',
        'Florance Slim Chair6',
      ],
    },
    floransSlim: {
      translateKey: 'floransSlim',
      tissues: [
        { imgName: 'Florance Slimmood', color: '#d4c2c0' },
        { imgName: 'Florance SlimmoodB', color: '#65868f' },
      ],
      size: 'Florance Slimrozmir',
      carousel: ['Florance Slim1', 'Florance Slim2', 'Florance Slim3', 'Florance Slim4', 'Florance Slim5', 'Florance Slim6'],
    },
    floransSlimSofa: {
      translateKey: 'floransSlimSofa',
      tissues: [{ imgName: 'Florance Slim sofamood', color: '' }],
      size: 'Florance Slim sofarozmir',
      carousel: ['Florance Slim sofa1', 'Florance Slim sofa2', 'Florance Slim sofa3', 'Florance Slim sofa4'],
    },
    fouette: {
      translateKey: 'fouette',
      tissues: [
        { imgName: 'Fouettemood', color: '#d8cbc2' },
        { imgName: 'FouettemoodY', color: '#cb8664' },
      ],
      size: 'fouete-rozmir',
      carousel: ['Fouette1', 'Fouette2', 'Fouette3', 'Fouette4', 'Fouette5', 'Fouette6', 'Fouette7', 'Fouette8'],
    },
    fouetteSofa: {
      translateKey: 'fouetteSofa',
      tissues: [{ imgName: 'Fouette Sofamood', color: '' }],
      size: 'foueteSofa-rozmir',
      carousel: ['Fouette Sofa1', 'Fouette Sofa2', 'Fouette Sofa3', 'Fouette Sofa4'],
    },
    lilibet: {
      translateKey: 'lilibet',
      tissues: [{ imgName: 'Lilibetmood', color: '' }],
      size: 'LilibetRozmir',
      carousel: ['Lilibet1', 'Lilibet2', 'Lilibet3', 'Lilibet4', 'Lilibet5'],
    },
    namurBedChair: {
      translateKey: 'namurBedChair',
      tissues: [{ imgName: 'Namur bed-chairmood', color: '' }],
      size: 'namurBedChairRozmir',
      carousel: ['Namur bed-chair1', 'Namur bed-chair2'],
    },
    namurBed: {
      translateKey: 'namurBed',
      tissues: [
        { imgName: 'Namurmood', color: '#a9988b' },
        { imgName: 'NamurmoodR', color: '#9b7b7e' },
      ],
      size: 'namurRozmir',
      carousel: ['Namur1', 'Namur2', 'Namur3', 'Namur4', 'Namur5', 'Namur6', 'Namur7', 'Namur8'],
    },
    namurSofa: {
      translateKey: 'namurSofa',
      tissues: [{ imgName: 'Namur Sofamood', color: '' }],
      size: 'namurSofaRozmir',
      carousel: ['NamurSofa1', 'NamurSofa2', 'NamurSofa3'],
    },
    namurLux: {
      translateKey: 'namurLux',
      tissues: [{ imgName: 'Namur-luxmood', color: '' }],
      size: 'namur-luxRozmir',
      carousel: ['Namur-lux1', 'Namur-lux2'],
    },
    parisBed: {
      translateKey: 'parisBed',
      tissues: [
        { imgName: 'Paris bedmood', color: '#d0c3b8' },
        { imgName: 'Paris bedmoodB', color: '#667585' },
        { imgName: 'Paris bedmoodR', color: '#9b7782' },
      ],
      size: 'ParisRozmir',
      carousel: ['Paris bed1', 'Paris bed2', 'Paris bed3', 'Paris bed4', 'Paris bed5', 'Paris bed6', 'Paris bed7'],
    },
    parisChair: {
      translateKey: 'parisChair',
      tissues: [{ imgName: 'Paris Chairmood', color: '' }],
      size: 'Paris-chairRozmir',
      carousel: ['Paris Chair1', 'Paris Chair2'],
    },
    parisPouf: {
      translateKey: 'parisPouf',
      tissues: [{ imgName: 'Paris poufmood', color: '' }],
      size: 'Paris poufrozmir',
      carousel: ['Paris pouf1', 'Paris pouf2', 'Paris pouf3'],
    },
    pomPonChair: {
      translateKey: 'pomPonChair',
      tissues: [{ imgName: 'Pom-pon chairmood', color: '' }],
      size: 'Pom-pon chairrozmir',
      carousel: ['Pom-pon chair1', 'Pom-pon chair2'],
    },
    pomPonDivan: {
      translateKey: 'pomPonDivan',
      tissues: [{ imgName: 'pom-pon divanmood', color: '' }],
      size: 'pom-pon divanrozmir',
      carousel: ['pom-pon divan1', 'pom-pon divan2', 'pom-pon divan3'],
    },
    pomPon: {
      translateKey: 'pomPon',
      tissues: [
        { imgName: 'Pom-ponmood', color: '#a29285' },
        { imgName: 'Pom-ponmoodY', color: '#c1938e' },
        { imgName: 'Pom-ponmoodB', color: '#a2a2ad' },
        { imgName: 'Pom-ponmoodBr', color: '#c8bfb9' },
      ],
      size: 'pom-ponRozmir',
      carousel: ['Pom-pon1', 'Pom-pon2', 'Pom-pon3', 'Pom-pon4', 'Pom-pon5', 'Pom-pon6', 'Pom-pon7', 'Pom-pon8', 'Pom-pon9', 'Pom-pon10'],
    },
    savoyaSoft: {
      translateKey: 'savoyaSoft',
      tissues: [{ imgName: 'Savoya Softmood', color: '' }],
      size: 'savoya SoftRozmir',
      carousel: ['Savoya Soft1', 'Savoya Soft2'],
    },
    savoya: {
      translateKey: 'savoya',
      tissues: [
        { imgName: 'Savoyamood', color: '#d0c3c2' },
        { imgName: 'SavoyamoodY', color: '#b59b52' },
      ],
      size: 'savoyaRozmir',
      carousel: ['Savoya1', 'Savoya2', 'Savoya3', 'Savoya4', 'Savoya5', 'Savoya6'],
    },
    sidneySofa: {
      translateKey: 'sidneySofa',
      tissues: [{ imgName: 'Sydney sofamood', color: '' }],
      size: 'Sydney sofarozmir',
      carousel: ['Sydney sofa1', 'Sydney sofa2', 'Sydney sofa3'],
    },
    sidney: {
      translateKey: 'sidney',
      tissues: [
        { imgName: 'Sidneymood', color: '#d2cbcb' },
        { imgName: 'SidneymoodG', color: '#5b7887' },
      ],
      size: 'sidneyRozmir',
      carousel: ['Sidney1', 'Sidney2', 'Sidney3', 'Sidney4', 'Sidney5', 'Sidney6', 'Sidney7', 'Sidney8', 'Sidney9'],
    },
    sidneyChair: {
      translateKey: 'sidneyChair',
      tissues: [{ imgName: 'SidneyChairmood', color: '' }],
      size: 'sidneyСRozmir',
      carousel: ['SidneyChair1', 'SidneyChair2', 'SidneyChair3', 'SidneyChair4'],
    },
    sidneyDivan: {
      translateKey: 'sidneyDivan',
      tissues: [{ imgName: 'SidneyDivanmood', color: '' }],
      size: 'sidneyDivanRozmir',
      carousel: ['SidneyDivan1', 'SidneyDivan2', 'SidneyDivan3', 'SidneyDivan4'],
    },
    laura: {
      translateKey: 'laura',
      tissues: [{ imgName: 'Lauramood', color: '' }],
      size: 'LauraRozmir',
      carousel: ['Laura1', 'Laura2', 'Laura3', 'Laura4', 'Laura5'],
    },
    komod: {
      translateKey: 'komod',
      tissues: [{ imgName: 'Komodmood', color: '' }],
      size: 'komodRozmir',
      carousel: ['komod1', 'komod2'],
    },
    komodCruls: {
      translateKey: 'komodCruls',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'komodCrulsRozmir',
      carousel: ['komodCruls1', 'komodCruls2'],
    },
    komodSteps: {
      translateKey: 'komodSteps',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'komod Stepsrozmir',
      carousel: ['komod Steps1', 'komod Steps2'],
    },
    perlaKomod: {
      translateKey: 'perlaKomod',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'komodPerla',
      carousel: ['Perlakomod'],
    },
    perla6Komod: {
      translateKey: 'perla6Komod',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'komod6Perla',
      carousel: ['Perla6komod'],
    },
    perla6: {
      translateKey: 'perla6',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'notImg',
      carousel: ['Perla-61', 'Perla-62'],
    },
    smartBlock: {
      translateKey: 'smartBlock',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Smart blockrozmir',
      carousel: ['Smart block1', 'Smart block2'],
    },
    table: {
      translateKey: 'table',
      tissues: [{ imgName: 'Table mood', color: '' }],
      size: 'Tablerozmir',
      carousel: ['Table1', 'Table2', 'Table3', 'Table4'],
    },
    perlaTable: {
      translateKey: 'perlaTable',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'PerlaTable',
      carousel: ['Perlatable1', 'Perlatable2'],
    },
    tumba: {
      translateKey: 'tumba',
      tissues: [{ imgName: 'Tumba mood', color: '' }],
      size: 'TumbaRozmir',
      carousel: ['Tumba1', 'Tumba2', 'Tumba3'],
    },
    tumbaCruls: {
      translateKey: 'tumbaCruls',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Tumba CrulsRozmir',
      carousel: ['Tumba Cruls1', 'Tumba Cruls2'],
    },
    perlaTumba: {
      translateKey: 'perlaTumba',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'TumbaPerla',
      carousel: ['Perla tumba'],
    },
    wardrobeCruls: {
      translateKey: 'wardrobeCruls',
      tissues: [{ imgName: 'Wardrobe Curlsmood', color: '' }],
      size: 'Wardrobe Curlsrozmir',
      carousel: ['Wardrobe Cruls1', 'Wardrobe Cruls2', 'Wardrobe Cruls3'],
    },
    wardrobeSteps: {
      translateKey: 'wardrobeSteps',
      tissues: [{ imgName: 'Wardrobe Stepsmood', color: '' }],
      size: 'Wardrobe Stepsrozmir',
      carousel: ['Wardrobe Steps1', 'Wardrobe Steps2', 'Wardrobe Steps3'],
    },
    wardrobeStrips: {
      translateKey: 'wardrobeStrips',
      tissues: [{ imgName: 'Wardrobe Stripsmood', color: '' }],
      size: 'Wardrobe Stripsrozmir',
      carousel: ['Wardrobe Strips1', 'Wardrobe Strips2', 'Wardrobe Strips3'],
    },
    wardrobeWaves: {
      translateKey: 'wardrobeWaves',
      tissues: [{ imgName: 'Wardrobe Wavesmood', color: '' }],
      size: 'Wardrobe Wavesrozmir',
      carousel: ['Wardrobe Waves1', 'Wardrobe Waves2', 'Wardrobe Waves3'],
    },
    perla030003: {
      translateKey: 'perla030003',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla0.3+0.0+0.3rozmir',
      carousel: ['Perla0.3+0.0+0.3'],
    },
    perla030303: {
      translateKey: 'perla030303',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla0.3+0.3+0.3rozmir',
      carousel: ['Perla0.3+0.3+0.3'],
    },
    perla0303: {
      translateKey: 'perla0303',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla0.3+0.3rozmir',
      carousel: ['Perla0.3+0.3'],
    },
    perla100010: {
      translateKey: 'perla100010',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla1.0+0.0+1.0rozmir',
      carousel: ['Perla1.0+0.0+1.0'],
    },
    perla1003: {
      translateKey: 'perla1003',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla1.0+0.3rozmir',
      carousel: ['Perla1.0+0.3'],
    },
    perla100310: {
      translateKey: 'perla100310',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla1.0+0.3+1.0rozmir',
      carousel: ['Perla1.0+0.3+1.01', 'Perla1.0+0.3+1.02', 'Perla1.0+0.3+1.03'],
    },
    perla1010: {
      translateKey: 'perla1010',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla1.0+1.0rozmir',
      carousel: ['Perla1.0+1.0'],
    },
    perla101010: {
      translateKey: 'perla101010',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla1.0+1.0+1.0rozmir',
      carousel: ['Perla1.0+1.0+1.0'],
    },
    perla1212: {
      translateKey: 'perla1212',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla1.2+1.2rozmir',
      carousel: ['Perla1.2+1.2'],
    },
    perla121212: {
      translateKey: 'perla121212',
      tissues: [{ imgName: 'mood', color: '' }],
      size: 'Perla1.2+1.2+1.2rozmir',
      carousel: ['Perla1.2+1.2+1.2'],
    },
    deepCover: {
      translateKey: 'deepCover',
      tissues: [
        { imgName: 'deepCovermood1', color: '#d6cfcd' },
        { imgName: 'deepCovermood2', color: '#c4cbcd' },
        { imgName: 'deepCovermood3', color: '#ece3e9' },
      ],
      size: 'deepCoverrozmir',
      carousel: ['deepCover1', 'deepCover2', 'deepCover3'],
    },
    diamondCover: {
      translateKey: 'diamondCover',
      tissues: [
        { imgName: 'Diamond covermood1', color: '#d6cfcd' },
        { imgName: 'Diamond covermood2', color: '#c4cbcd' },
        { imgName: 'Diamond covermood3', color: '#ece3e9' },
      ],
      size: 'Diamond coverrozmir',
      carousel: ['Diamond cover1', 'Diamond cover2', 'Diamond cover3'],
    },
    linenBedding: {
      translateKey: 'linenBedding',
      tissues: [
        { imgName: 'linen beddingmood1', color: '#d9d3d0' },
        { imgName: 'linen beddingmood2', color: '#b1ada5' },
        { imgName: 'linen beddingmood3', color: '#a8b3ca' },
        { imgName: 'linen beddingmood4', color: '#baa7a7' },
      ],
      size: 'linen beddingrozmir',
      carousel: ['linen bedding1', 'linen bedding2'],
    },
    milletCover: {
      translateKey: 'milletCover',
      tissues: [
        { imgName: 'Millet covermood1', color: '#d9d3d0' },
        { imgName: 'Millet covermood2', color: '#afb9bf' },
        { imgName: 'Millet covermood3', color: '#c4b9bc' },
      ],
      size: 'Millet coverrozmir',
      carousel: ['Millet cover1', 'Millet cover2'],
    },
    percaleBedLinens: {
      translateKey: 'percaleBedLinens',
      tissues: [
        { imgName: 'percale bed linensmood1', color: '#dad2d0' },
        { imgName: 'percale bed linensmood2', color: '#dcdcdc' },
        { imgName: 'percale bed linensmood3', color: '#bdc8ce' },
        { imgName: 'percale bed linensmood4', color: '#cfc6bd' },
      ],
      size: 'percale bed linensrozmir',
      carousel: ['percale bed linens1', 'percale bed linens2'],
    },
    snowCover: {
      translateKey: 'snowCover',
      tissues: [
        { imgName: 'Snow covermood1', color: '#d7d1cf' },
        { imgName: 'Snow covermood2', color: '#bbc2c5' },
        { imgName: 'Snow covermood3', color: '#c5babf' },
      ],
      size: 'Snow coverrozmir',
      carousel: ['Snow cover1', 'Snow cover2', 'Snow cover3'],
    },
    zigZagCover: {
      translateKey: 'zigZagCover',
      tissues: [
        { imgName: 'Zig-zag covermood1', color: '#dad3d1' },
        { imgName: 'Zig-zag covermood2', color: '#d0d7d9' },
        { imgName: 'Zig-zag covermood3', color: '#ddd6de' },
      ],
      size: 'Zig-zag coverrozmir',
      carousel: ['Zig-zag cover1', 'Zig-zag cover2', 'Zig-zag cover3'],
    },
  }),

  getters: {
    getProduct: (state) => (productId) => {
      return state[productId];
    },
  },
};
